name: 🐍 Generate Contribution Snake

# Запуск:
on:
  schedule:
    - cron: '0 4 * * *'      # по UTC раз в сутки в 04:00
  workflow_dispatch:         # кнопку "Run workflow" в разделе Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/generate-snake-game-from-github-contribution-grid@v3.3.0
        with:
          username: Akim-norfeg       # ваш GitHub username
          token: ${{ secrets.GITHUB_TOKEN }}
          output-format: svg          # или "gif"
          # Название файла, который появится в корне
          output-file: contrib-snake.svg
