name: 🐍 Generate Contribution Snake

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: akim-norfeg
          output-format: svg
          output-file: contrib-snake.svg

      - name: Debug: list files
        run: |
          echo "Files now in repo:"
          ls -R .

      - name: Commit & Push contrib-snake.svg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add contrib-snake.svg
          git diff --cached --quiet || git commit -m "chore: update contribution snake"
          git push origin HEAD:main
